kind: pipeline
name: production

steps:
- name: now
  image: one000mph/drone-now
  environment:
      NOW_TOKEN:
          from_secret: vercel_token
  settings:
      secret:
          front_secret: vercel_token
      deploy_name: team-kat-web
      prod: true
trigger:
  branch:
  - master
